### PR TITLE
fixed logos

### PR DESCRIPTION
**Pull request by winniedresden**
fixed the logos so they don't cut off on the bottom (for the ok website)

### CODE REVIEW

**Comment by biglovisa** [comment]
@winniedresden can you include screenshots of what it looks like?

**Review by biglovisa — APPROVED** [review]

**Comment by winniedresden** [comment]
> @winniedresden can you include screenshots of what it looks like?

Screen Shot 2021-05-06 at 9 14 45 PM
Screen Shot 2021-05-06 at 9 14 35 PM

**Comment by biglovisa** [comment]
@winniedresden can we add some spacing to the left of the Toggle Theme button so it's not right up against the side of the window? 

I'm wondering if the oK logo and the button would look better if they had the same height... 👀 It might make the left bottom footer look sleeker.

**Comment by winniedresden** [comment]
Do you like this? Or is this too small?

[cid:FE7DD88D-F637-41CF-AEE9-F678F748C046]

On May 7, 2021, at 12:41 AM, Lovisa Svallingson ***@***.******@***.***>> wrote:



@winniedresden<https://github.com/winniedresden> can we add some spacing to the left of the Toggle Theme button so it's not right up against the side of the window?

I'm wondering if the oK logo and the button would look better if they had the same height... 👀 It might make the left bottom footer look sleeker.

**Comment by biglovisa** [comment]
@winniedresden I might be missing something but I don't see the screenshot attached?

**Comment by winniedresden** [comment]
> > @winniedresden can you include screenshots of what it looks like?
> 
> Screen Shot 2021-05-06 at 9 14 45 PM
> Screen Shot 2021-05-06 at 9 14 35 PM

do you like this spacing on the left? Like that far from the left of the screen? 

Screen Shot 2021-05-07 at 10 16 51 AM

**Comment by biglovisa** [comment]
@winniedresden that looks good! We might want to round the edges of that button, but we can do that in a later PR.

**Comment by biglovisa** [comment]
Let's merge it!

**Pull request merged**
